version: "3"

services:

  web:
      image: webdevops/php-nginx:7.2
      volumes:
          - ./:/app
      working_dir: /app
      env_file: .env
      depends_on:
          - database
      environment:
          WEB_DOCUMENT_ROOT: /app/public
          WEB_DOCUMENT_INDEX: index.php
          PHP_DATE_TIMEZONE: "Europe/Paris"
          PHP_DISPLAY_ERRORS: 1

  database:
      image: mysql:5.7
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydatabase
