users:
  type: rest
  resource: App\Controller\UsersController

articles:
  type: rest
  resource: App\Controller\ArticlesController

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
